version: 2
updates:
  # Frontend: Monitor npm dependencies
  - package-ecosystem: "npm"
    directory: "/crm" # ✅ This ensures Dependabot scans package.json inside frontend
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
    assignees:
      - "Masked-Kunsiquat"

  # Backend: Monitor PocketBase updates (if using Go modules)
#  - package-ecosystem: "gomod"
#    directory: "/backend" # ✅ If backend uses Go modules, Dependabot will scan go.mod
#    schedule:
#      interval: "weekly"
#    open-pull-requests-limit: 5
#    labels:
#      - "dependencies"
#      - "backend"

  # GitHub Actions (if you have workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
