name: Auto-approve Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  approve:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.BOT_APPROVE_TOKEN }}
